on:
  push:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Checkout Mangio repository
        uses: actions/checkout@v3
        with:
          repository: 'Mangio621/Mangio-RVC-Fork'
          path: 'mangio'
      
      - name: Check the latest commit
        run: |
          export MANGIO_COMMIT=$(git -C mangio rev-parse HEAD)
          echo "Mangio commit: $MANGIO_COMMIT"
          echo "MANGIO_COMMIT=$MANGIO_COMMIT" >> $GITHUB_ENV

      - name: Update the latest commit in repository variables
        uses: action-pack/set-variable@v1
        if: ${{ vars.LATEST_MANGIO_COMMIT != env.MANGIO_COMMIT || github.event_name != 'schedule' }}
        with:
          name: 'LATEST_MANGIO_COMMIT'
          value: ${{ env.MANGIO_COMMIT }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      
      - name: Login to ghcr registry
        uses: docker/login-action@v2
        if: ${{ vars.LATEST_MANGIO_COMMIT != env.MANGIO_COMMIT || github.event_name != 'schedule' }}
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}
      
      - name: Build image
        if: ${{ vars.LATEST_MANGIO_COMMIT != env.MANGIO_COMMIT || github.event_name != 'schedule' }}
        run: |
          docker build -t ghcr.io${{ secrets.GH_USERNAME }}/mangio-rvc-docker:${{ env.MANGIO_COMMIT }} -t ghcr.io${{ secrets.GH_USERNAME }}/mangio-rvc-docker:latest .
      
      - name: Push image
        if: ${{ vars.LATEST_MANGIO_COMMIT != env.MANGIO_COMMIT || github.event_name != 'schedule' }}
        run: |
          docker push ghcr.io${{ secrets.GH_USERNAME }}/mangio-rvc-docker:${{ env.MANGIO_COMMIT }}
          docker push ghcr.io${{ secrets.GH_USERNAME }}/mangio-rvc-docker:latest
        